### ISSUE TITLE
"A JavaScript Error Ocurred In The Main Process"

### ISSUE THREAD

**Issue by Brittank88** [crazy-max/discord-ptb-portable#2]
Hi there,

I've been trying to install the latest version of Discord-PTB-Portable (version 0.0.34-5 specifically), however, 2 large errors occur when I initially run the newly installed application:

The first error:
![image](https://user-images.githubusercontent.com/24266948/32409098-4c3f5f20-c1f9-11e7-8f01-0c67f9f9d4e8.png)

The second error:
![image](https://user-images.githubusercontent.com/24266948/32409101-55c7a66a-c1f9-11e7-9042-3cb563a6d855.png)

These both may very well be the same error, but I've put them here just in case.

Once again, these errors are occurring when I initially run the newly installed app, and it is downloading/installing updates from discord.

I don't really have a clue as to what could be causing these errors. The location I'm installing PortableDiscord on is just a partition of my main hard drive, and I've tried both running the files with and without administrator, to no avail. Not even after following the advice at https://support.discordapp.com/hc/en-us/articles/209099387--Windows-Installer-Update-failed- does it work.

The strangest thing is that after the errors, discord does actually open. However, if I close it and try to open it again, or attempt to install BetterDiscord into it, it totally breaks with similar-looking JavaScript errors.

Anyway, thanks for your time.

**Comment by crazy-max** [comment]
Hi @Brittank88,

I've abe to reproduce your issue.
I'll keep you in touch!

**Comment by Brittank88** [comment]
Thanks @crazy-max !

Heads up - this also happens for normal Discord. I have no idea what the issue is, but it's with every single discord setup, whether it be your portable editions or the actual original editions.

Hopefully a fix can be found ;;

**Comment by crazy-max** [comment]
It's a bug from Discord actually.
But i can bypass this bug via the portable exe.

**Comment by Brittank88** [comment]
Fantastic! Thanks for helping out!

**Comment by crazy-max** [comment]
Only related to PTB releases. Can you confirm on your side pls ?

**Comment by Brittank88** [comment]
As in, check whether this only happens with PTB?

I've already tried with PTB and just with normal Discord or even Discord Canary, all versions have errors.

**Comment by crazy-max** [comment]
Ok thanks, i will investigate on it

**Comment by crazy-max** [comment]
@Brittank88 Can you try with the latest pre-release : https://github.com/crazy-max/discord-ptb-portable/releases/tag/0.0.36-7 ?

**Comment by Brittank88** [comment]
Awesome!! It worked perfectly!

**Comment by Brittank88** [comment]
I'm just attempting to install betterdiscord now...

**Comment by crazy-max** [comment]
@Brittank88 Yes i've got this issue some time ago.
You can check and/or post an issue on the [official repository](https://github.com/Jiiks/BetterDiscordApp/issues).
Keep me in touch ;)

**Comment by Brittank88** [comment]
Thanks, will do :)

**Comment by Gamerbiomek2** [comment]
has happened again when it starts up now
![Discord PTB javaScript error](https://user-images.githubusercontent.com/22333494/93727172-e9ce7580-fb87-11ea-8acf-78997a97a30a.png)
